name: Bump vul

on:
  workflow_dispatch:
    inputs:
      vul_version:
        required: true
        type: string
        description: the vul version

run-name: Bump vul to v${{ inputs.vul_version }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Vul versions
        run: |
          sed -r -i "s/ghcr.io\/khulnasoft-lab\/vul:[0-9]+\.[0-9]+\.[0-9]+/ghcr.io\/khulnasoft-lab\/vul:${{ inputs.vul_version }}/" Dockerfile
          sed -r -i "s/VUL_VERSION: [0-9]+\.[0-9]+\.[0-9]+/VUL_VERSION: ${{ inputs.vul_version }}/" .github/workflows/build.yaml
          find test/data -type f -name '*.test' | xargs sed -r -i 's/"version": "[0-9]+\.[0-9]+\.[0-9]+"/"version": "${{ inputs.vul_version }}"/'

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          title: "chore(deps): Update vul to v${{ inputs.vul_version }}"
          commit-message: "chore(deps): Update vul to v${{ inputs.vul_version }}"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch-suffix: timestamp
          branch: bump-vul
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
